#define COMPONENT diving_basic

#include "\x\enhanced_diving\Addons\main\script_mod.hpp"
#include "\x\enhanced_diving\Addons\main\script_macros.hpp"

#define DISPLAY_DIVING_COMPUTER_IMAGE_IDC         1110
#define DISPLAY_DIVING_DISTANCE_UNIT_IDC          1111
#define DISPLAY_DIVING_DECO_TAG_IDC               1112
#define DISPLAY_DIVING_HEIGHT_IDC                 1113
#define DISPLAY_DIVING_DECO_FREE_TIME_IDC         1114
#define DISPLAY_DIVING_TIME_TO_SURFACE_TEXT_IDC   1115
#define DISPLAY_DIVING_DIVE_TIME_IDC              1116
#define DISPLAY_DIVING_TIME_TO_SURFACE_IDC        1117
#define DISPLAY_DIVING_DIVING_TIME_IDC            1118
#define DISPLAY_DIVING_O2_PERCENTAGE_IDC          1119
#define DISPLAY_DIVING_PRESSURE_UNIT_IDC          1120
#define DISPLAY_DIVING_TIME_TEXT_IDC              1121
#define DISPLAY_DIVING_PRESSURE_VALUE_IDC         1122
#define DISPLAY_DIVING_TIME_NUMBER_IDC            1123
#define DISPLAY_DIVING_DEEP_STOP_IDC              1124
#define DISPLAY_DIVING_EMERGENCY_TEXT_IDC         1125
#define DISPLAY_DIVING_EMERGENCY_DEPTH_IDC        1126
#define DISPLAY_DIVING_EMERGENCY_TIME_IDC         1127
#define DISPLAY_DIVING_ASENDBAR_IDC               1128
#define DISPLAY_DIVING_N2_BAR_IDC                 1129
#define DISPLAY_DIVING_EMERGENCY_ARROW_UP_IDC     1130
#define DISPLAY_DIVING_EMERGENCY_ARROW_DOWN_IDC   1131
#define DISPLAY_DIVING_SHOW_CHOOSEN_TANK_IDC      1132
